# Generated by Django 4.1.2 on 2022-11-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figurines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NacionalTeam',
            new_name='NationalTeam',
        ),
    ]
